services:
  backend:
    build: ./backend
    command: "npm run start"
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - streamers-db:/etc/database
    
  frontend:
    build: ./frontend
    command: "npm run dev"
    ports:
      - 3000:3000
    working_dir: /app

volumes:
  streamers-db:
    external: false