services:
  backend:
    build: ./backend
    container_name: streamer-backend
    command: "pnpm start:docker"
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      # - /app/prisma
      - /app/node_modules
      - /app/.next
      - streamers-db:/etc/database
    depends_on:
      - frontend
    tty: true
    stdin_open: true

  frontend:
    container_name: streamer-web
    build: 
      context: ./frontend
      target: dev
    environment:
      - WATCHPACK_POLLING=true
      - BACKEND_URL=backend
      # - NODE_OPTIONS=--max-old-space-size=4096
    command: "pnpm dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  streamers-db:
    external: false